layout_spectrum: 1
typography_spectrum: 0.8085107
color:
  saturation: 0.4978724
  lightness: 0.1617021
  brandStrength: 0
  rhythmicContrast: 0.6978723
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: 'Wiseyesmedia '
